site_name: Darsana's Site
theme:
  name: material
  dark_mode: true
  sticky_navigation: false
  highlightjs: true
  config: {} # Use an empty mapping if no specific options are needed under config

nav:
  - Introduction: index.md
  - Professional Info:
    - Curriculum Vitae: Curriculum Vitae.md
    - Skill Set: Skillset.md
    - Sample Works: Sample.md
  - Personal Info: Personal.md
  - About This Site:
    - Site Info: AboutSite.md
    - Copyright: DoNotCopy.md
  - Appendix:
    - FAQs: FAQs.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - toc:
      permalink: true

extra_javascript:
  - Styles.js
extra_css:
  - styles.css
extra:
  version:
    provider: mike
  generator: false
copyright: Copyright &copy; 2025 Darsana KS | All Rights Reserved.